Add send redemption ltm
somosprte/lmb-developers pull request #1
Opened 2021-07-19 13:18 UTC by CamargoKmila

## Objetivo
Criar a integração do motor de Fidelidade com a contabilidade "CAR".

## Descrição
Link no Jira: https://prte.atlassian.net/browse/LER-2310

2021-07-19 14:05 UTC, pedrorenan requested changes
https://www.loom.com/share/812811a447234a12b29b3e0f7c75ca79

2021-07-20 19:03 UTC, CamargoKmila commented
> https://www.loom.com/share/812811a447234a12b29b3e0f7c75ca79

Foi alterado o nome do método e a chamada para o payload que faltava. Os campos do payload repassados na documentação pela leroy são definidos na API fidelidade seguindo o padrão dos métodos já implementados.

2021-07-21 14:37 UTC, pedrorenan requested changes
Gentileza colocar o nome da pull request no padrão da PRTE

2021-07-22 12:43 UTC, pedrorenan commented
O payload descrito na atividade está diferente do implementado.

2021-07-28 21:55 UTC, merged